app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    fanoutexchange: spring-boot-fanoutexchange
    topicexchange: spring-boot-topicexchange
    queue: user.queue
    routingkey: user.routingkey
server:
  port: 9091
